### ISSUE TITLE
Daemon started twice

### ISSUE THREAD

**Issue by jonathanhoskin** [opscode-cookbooks/memcached#43]
On Ubuntu 14.04 with memcached cookbook v1.7.2. I'm using the cookbook like this:

    memcached_instance 'my_memcached'

.. with these attributes:

    default['memcached']['memory'] = 64
    default['memcached']['logfilename'] = 'memcached.log'
    default['memcached']['port'] = 11211
    default['memcached']['user'] = 'memcache'

After converge, I end up with two lots of memcached running. It's like the default Ubuntu installer is also starting up it's own init script?

    $ ps aux | grep memcached
    memcache  1619  0.0  0.0 325396  1184 ?        Sl   23:01   0:00 /usr/bin/memcached -m 64 -p 11211 -u memcache -l 127.0.0.1
    root      1707  0.0  0.0    168     4 ?        Ss   23:02   0:00 runsv memcached-my_memcached
    memcache  1718  0.0  0.0  54820  1024 ?        Sl   23:02   0:00 /usr/bin/memcached -v -m 64 -U -p 11211 -u memcache -l 0.0.0.0 -c 1024
    root      1745  0.0  0.0    184     4 ?        S    23:02   0:00 svlogd -tt /var/log/memcached-my_memcached

**Comment by stonith** [comment]
This should be addressed by #47. Please reopen if incorrect.
